// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAujUIIMkBS8DFFcIK9Yf_N8Qc4czcFCqg',
    appId: '1:775128372872:web:c66511e6e10eb785bf313d',
    messagingSenderId: '775128372872',
    projectId: 'sclearance-c1f64',
    authDomain: 'sclearance-c1f64.firebaseapp.com',
    storageBucket: 'sclearance-c1f64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1BPIhdSrNDcmRb8CyldCXglqKeYKQZo',
    appId: '1:775128372872:android:e0be1a714c924cd0bf313d',
    messagingSenderId: '775128372872',
    projectId: 'sclearance-c1f64',
    storageBucket: 'sclearance-c1f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnA0gzvdYMAhsVJXQB-TcQdBfO0N7DeM',
    appId: '1:775128372872:ios:97ef4663d555800cbf313d',
    messagingSenderId: '775128372872',
    projectId: 'sclearance-c1f64',
    storageBucket: 'sclearance-c1f64.appspot.com',
    iosClientId: '775128372872-vjml3vc6kh4urie75t35u95f7q7v49vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentClearanceApplication',
  );
}
